### PR TITLE
Change Square Crypto to Spiral

### PR DESCRIPTION
**Pull request by MarnixCroes**
Square Crypto is now Spiral

### CODE REVIEW

**Review by afilini — APPROVED** [review]
<s>ACK 1a5da68ffaa08138c05b398acadfe94666a1b8c2</s>

**Review by afilini — CHANGES_REQUESTED** [review]
No sorry, I think you forgot to push the new image. Your code references `/img/spiral.svg` but it's not present.

**Comment by MarnixCroes** [comment]
@afilini thanks!
Should be fixed now

**Review by notmandatory — APPROVED** [review]
ACK 71f14593b3a9715abaae84d4a4af29f8880fb7e6

Looks good on the preview: 
https://deploy-preview-86--awesome-golick-685c88.netlify.app/supporters/

**Review by afilini — APPROVED** [review]
ACK 71f14593b3a9715abaae84d4a4af29f8880fb7e6

**Pull request merged**
