### PR TITLE
Hidden power of bitcoin using descriptors and miniscript

### PR DESCRIPTION
**Pull request by rajarshimaitra**
This PR updates https://github.com/bitcoindevkit/bitcoindevkit.org/pull/53 to latest changes and updated doc site.

Original description by @sandipndev 

In this blog, I have introduced the idea of a descriptor, made a multisig descriptor wallet and tested miniscript policies.
This is a very beginner's take on all these topics.
Hope you guys like it.

### CODE REVIEW

**Review by sandipndev — COMMENTED** [review]
Thank you for the refactor and updates, @rajarshimaitra.

I will give the commands a go once again today, hope everything works fine.

**Comment by thunderbiscuit** [comment]
This is ready for merge IMO. I found a few typos but nothing blocking. 👍

**Comment by rajarshimaitra** [comment]
Can we please have this merged?? This is one of the best blog on descriptors out there and this needs to be seen..

**Comment by notmandatory** [comment]
Sorry for the delay, and thanks for the reminder, published now!

**Pull request merged**
