### PR TITLE
Add 2024 Q2 update blog post

### PR DESCRIPTION
**Pull request by thunderbiscuit**
I used to have a workflow to build the site locally but it doesn't work anymore so I don't have a way to test this. Pushing here so I can see the preview.

Edit: ok it's not just on my machine.

So the key is to add
```js
function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
```

To the `node_modules/@spiralbtc/vuepress-devkit-theme/config.js` file to enable it to build locally. For deployment, we'd need to update the theme itself, but I can't find the github link! @dennisreimann any ideas?

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
Consider adding the new example applications:

1. https://github.com/bitcoindevkit/BDKSwiftExampleWallet
2. https://github.com/bitcoindevkit/bdk-kotlin-example-wallet

**Review by reez — APPROVED** [review]
ACK cfb9c26c5767ebc6fcdff6f841c204fa1d1bea65

ACKing because the text of this looks good, even though I see CI is failing and your comment and that I can't see a preview of this yet.

**Review by notmandatory — APPROVED** [review]
ACK cfb9c26c5767ebc6fcdff6f841c204fa1d1bea65

**Comment by thunderbiscuit** [comment]
@dennisreimann actually after rebasing on your PR, I still get the error, even though our package-lock shows 
```json
"@spiralbtc/vuepress-devkit-theme": "^0.19.0",
```

**Comment by dennisreimann** [comment]
@thunderbiscuit You are correct, the reference for the `capitalize` function was indeed missing from the theme config. I'm not sure why the error comes upin context of this PR only, but it must have something to do with the pagination, where `capitalize` gets used.

However, I've updated the theme and used the new version here, now the build and preview work again. Blog post preview here: https://deploy-preview-189--awesome-golick-685c88.netlify.app/blog/_2024-q2-update/

**Comment by thunderbiscuit** [comment]
Sweet thanks @dennisreimann!

**Pull request merged**
