### PR TITLE
Add page for case studies

### PR DESCRIPTION
**Pull request by thunderbiscuit**
This PR adds a page where we showcase companies and projects building using the Bitcoin Development Kit.

The outline for this is taken from lightningdevkit/lightningdevkit.org#203.

### CODE REVIEW

**Comment by notmandatory** [comment]
Concept ACK! I've added two teams that have agreed to be featured to the discussion board: https://github.com/orgs/bitcoindevkit/discussions/64

**Comment by thunderbiscuit** [comment]
## Currently reaching out to
- [x] Peach Wallet
- [x] Anchor Watch
- [x] Seba Bank
- [x] Mutiny Wallet
- [x] Lava
- [x] Bitkey
- [x] Bitmask
- [x] Galoy
- [x] Bull Bitcoin
- [x] LDK-node
- [x] Foundation Devices (Envoy)
- [ ] Lipa
- [x] Padawan Wallet
- [ ] Pocket Bitcoin

## Agreed/Declined
✅ Padawan Wallet
✅ Peach Wallet
✅ LDK-Node
✅ Bitkey
✅ Lava
✅ Seba Bank
✅ Anchor Watch
✅ Mutiny Wallet

**Comment by moneyball** [comment]
I spoke with Lava and they'd love to be part of this.

What's the status of this? Would be great to get it launched. It is nice having an easily shareable showcase for LDK https://lightningdevkit.org/case-studies/

**Comment by thunderbiscuit** [comment]
Awesome to hear from Lava! 

The current status is that I've been using a template that Haley provided me (the one she used for LDK) and started filling it out. My latest round of contacts were Lipa, Galoy, Seba, and Pocket Bitcoin. I have not heard back yet (it's been about2 weeks now) but I think I will reach out on official emails instead of informal Twitter/Discord messages (if you're not friends on Discord I think messages sometimes get lost; same for reaching out to Twitter handles).

**Comment by thunderbiscuit** [comment]
I'm changing my mind on this PR. I initially wanted to have all orgs before merging, but now that we have a good start with 8 projects, why not merge this now and we'll add to it in the following weeks as the rest of the answers come in? I also think it might be easier to get responses once we have a working example with an already very strong group of projects on the page already. 

How does that sound? I'm worried of just waiting for perfection when we have a great page already. @notmandatory @moneyball any opinion on this?

FYI even if you agree @notmandatory don't merge just yet I need to clean up the logos to make them all the same size.

**Comment by moneyball** [comment]
Agree but perhaps do one more round of outreach to those who have yet to respond and provide a deadline (eg 1 week). Also if some are unresponsive let me know and I can try too.

(for LDK we got 100% participation pre-launch)

**Review by realeinherjar — APPROVED** [review]
As discussed in W38 Language Bindings Dev Call, we need a tracking issue with the ones that we haven't got feedback on the showcase permission.

ACK a2053e0307d16b59ffd7ffc0994ba5b1a5934062.

**Comment by thunderbiscuit** [comment]
I received a recommendation to tag developers directly here instead of writing emails as devs check their GitHub accounts more than their emails 🤣.

Some projects we'd love to include on the page (please let us know if someone else on your team is a better contact!):

Galoy: @bodymindarts
Bitmask: @cryptoquick
Pocket Bitcoin: @vesparny
Bull Bitcoin: @BullishNode
Foundation Devices: @icota
Lipa: @gcomte @danielgranhao
Stackmate: @i5hi

If you'd be so kind as to give us the thumbs up to be added on the page, we'll pull your logo from your website and the tagline for your project! (feel free to provide us with a custom tagline as well). I'll leave this PR open for another week; if you can get back to us within that timeframe that'd be perfect, otherwise it's not a problem! We can add you in on later PRs to the website.

Note: you can [see what the page looks like on this preview](https://deploy-preview-148--awesome-golick-685c88.netlify.app/case-studies/).

**Comment by thunderbiscuit** [comment]
Will reach out to [Lexe](https://lexe.app/)

Twitter announcement: [link](https://x.com/lexeapp/status/1704643361548996879)

**Comment by moneyball** [comment]
@thunderbiscuit you can also reach out via Twitter/X, Discord, etc.

**Comment by icota** [comment]
@thunderbiscuit we'd love to be included!

You can fetch the logo from the stores eg. https://apps.apple.com/hr/app/envoy-by-foundation/id1584811818 and the best tagline we could come up with is:
> Envoy By Foundation
> A Bitcoin wallet with powerful account management and privacy features. Use alongside your Passport hardware wallet to take true ownership of your Bitcoin.

Thanks!

**Comment by thunderbiscuit** [comment]
Envoy by Foundation Devices is added!

Re: reaching out through Discord/Twitter, yep that's exactly what I did for the first round. I think the low response rate might have been because on Discord and Twitter, DMs go to special side places if the person reaching out is not a friend (Discord) or if you don't follow them (Twitter). I suspect some of these messages never got seen at all and just got lost in the sauce. I'll reach out over email next after this round!

**Review by notmandatory — APPROVED** [review]
ACK b8b2d1c79124fa0fcac61d1b4819ea0a9c0e241b

Looks great!

**Comment by BullishNode** [comment]
Bull Bitcoin:
"A self-custodial Bitcoin Wallet and Exchange app that lets users buy, sell, spend and get paid with Bitcoin. Bitcoins are automatically sent from the exchange to the user's wallet."

red bull + white text


Thanks @thunderbiscuit

**Comment by cryptoquick** [comment]
Hi, I'd be happy to have you add [BitMask](https://bitmask.app) as well.

Here are our logos:

BitMask logo white
BitMask logo black

**Pull request merged**
