### PR TITLE
docs/bdk-cli/README.md: add link to /introduction

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
In certain browser window dimensions - a menu is not presented.
Adding a link to the introduction ensures the viewer can navigate off the BDK-CLI stub page.

Screen Shot 2023-11-28 at 7 15 38 PM

**Comment by RandyMcMillan** [comment]
Another option would be to simply point to the introduction page in the navigation. Maybe renaming it BDK-CLI.md

Happy to implement the optional idea.

**Comment by RandyMcMillan** [comment]
preview link:

https://deploy-preview-164--awesome-golick-685c88.netlify.app/bdk-cli/

bdk-cli-pr-164

**Comment by thunderbiscuit** [comment]
Hey! Sorry I'm not getting to this very quickly. How do you get to root this page from a navigation standpoint? I can't find a way to get to it directly other than typing the full `bdk-cli/` path in my browser... I wonder if this is a sort of phantom page we should just remove (as per your suggestion above).

**Comment by RandyMcMillan** [comment]
I will take another look.

**Review by thunderbiscuit — APPROVED** [review]

**Pull request merged**
