### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by dennisreimann**
Fixes the build issues in #189.

@thunderbiscuit Can you check if this resolves the build error for you and if so merge this and then rebase your blog PR on top of the fix?

@ConorOkus updated the spiral theme and the latest version already includes the missing function. For reference: The theme is maintained here: https://github.com/spiralxyz/vuepress-devkit-theme

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
Wow thanks for the super quick fix!

ACK a5317cc58a6b794bc49fc2ea2f4e03502ff4cb65. I see why I couldn't find it; I'm not part of the spiralxyz org. All is good now!

**Review by thunderbiscuit — APPROVED** [review]

**Comment by thunderbiscuit** [comment]
Ok actually it only worked locally because I had added the method to my local theme. When I remove the function it still doesn't build, even though my package-lock shows 
```json
"@spiralbtc/vuepress-devkit-theme": "^0.19.0",
```

**Comment by dennisreimann** [comment]
Did you run `npm install` to upgrade the dependencies locally?

**Comment by thunderbiscuit** [comment]
I had not! Thanks. But actually even after doing that I get the same error. Both my package.json and package-lock.json use the `"@spiralbtc/vuepress-devkit-theme": "^0.19.0",` dependency.

It also appears that it's breaking for Netlify (#189).

**Pull request merged**
