### PR TITLE
Remove duplicate setState in Create Wallet button + no_leading_underscores_for_local_identifiers for formKey

### PR DESCRIPTION
**Pull request by kumulynja**
This pull request removes the setState in the callback of the "Create Wallet" button since the setState is also done in the `createOrRestoreWallet` function already in that same button callback.

It also changes _formKey to formKey since local identifiers in dart should not have leading underscores.

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
Is this PR still relevant? @kumulynja @BitcoinZavior please advise. I'd like to get this merged or closed if not relevant anymore given the new tutorial content PR.

**Comment by kumulynja** [comment]
> Is this PR still relevant? @kumulynja @BitcoinZavior please advise. I'd like to get this merged or closed if not relevant anymore given the new tutorial content PR.

The setState issue seems to have been fixed on master already, the formKey still has an underscore in front, this gave problems when running the example at the time, so I think that is still relevant, but I should run the latest version again to be sure about that.

**Comment by thunderbiscuit** [comment]
Make sure to rebase your PR as well, as I merged some other fixes to that tutorial a few days ago.

**Comment by BitcoinZavior** [comment]
> 

Hi, @kumulynja thanks.
Please try and run the latest version again and if it works you can close the PR.

**Pull request closed without merging**
