### PR TITLE
Vuepress migration

### PR DESCRIPTION
**Pull request by dennisreimann**
Work in progress PR for the upcoming migration to Vuepress. Putting this out there for transparency -- you can check out the [Netlify preview](https://bdk-docs-preview.netlify.app/) and provide feedback.

### CODE REVIEW

**Comment by RCasatta** [comment]
I have seen blog post links are changed (they are now without the /{year}/{month}/ part).

I think we need to keep the links the same so that search engines and existing backlinks to the site are preserved. Another issue is that some links in the articles may be broken, see for example the link of other parts in the series in https://bdk-docs-preview.netlify.app/blog/fee-estimation-for-light-clients-part-3/

**Comment by dennisreimann** [comment]
@RCasatta Thanks for the pointer, I fixed the URLs by setting them to the previous ones!

**Comment by dennisreimann** [comment]
Rebased with current master, now the [Playground](https://bdk-docs-preview.netlify.app/bdk-cli/playground/) is also integrated via iframe.

**Review by notmandatory — APPROVED** [review]
ACK, looks good, thanks!

**Pull request merged**
