### PR TITLE
bdk-cli basics multi-sig 2 of 3

### PR DESCRIPTION
**Pull request by logosstone**
bdk-cli basics multi-sig 2 of 3 Testnet

### CODE REVIEW

**Comment by notmandatory** [comment]
For the tutorial section you also need to edit the const tutorialSidebar variable in the docs/.vuepress/config.js file
just add the path to your page. And if you want to you can create a directory and _index.md file in the content/authors directory, but that's optional.

**Comment by logosstone** [comment]
> For the tutorial section you also need to edit the const tutorialSidebar variable in the docs/.vuepress/config.js file just add the path to your page. And if you want to you can create a directory and _index.md file in the content/authors directory, but that's optional.

That was it, thank you @notmandatory 💯.

**Comment by thunderbiscuit** [comment]
Is this ready for review @waterst0ne? I can take a look and make modifications if required if you think it's ready to go.

**Comment by logosstone** [comment]
> Is this ready for review @waterst0ne? I can take a look and make modifications if required if you think it's ready to go.

This is ready. Please review and make the required changes. Thank you.

**Review by thunderbiscuit — APPROVED** [review]
ACK.

**Pull request merged**
