### PR TITLE
foundation: updated grantees page as of q4 2024

### PR DESCRIPTION
**Pull request by reez**
Updating Grantees page to reflect Q4 2024

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
Looks good to me. Ping me when you have the updated text for the project grantees and I'll ACK.

**Comment by reez** [comment]
> Looks good to me. Ping me when you have the updated text for the project grantees and I'll ACK.

Great! Cool, just reached out to them on Discord, will do-

**Comment by reez** [comment]
> Looks good to me. Ping me when you have the updated text for the project grantees and I'll ACK.

@thunderbiscuit got the updated text for project grantees now-

**Review by thunderbiscuit — APPROVED** [review]
ACK 6130546b29af2bf8219f92a3854c57a3211b437d.

**Pull request merged**
