### PR TITLE
Bdk flutter tutorial

### PR DESCRIPTION
**Pull request by BitcoinZavior**
Added BDK-Flutter Tutorial

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
I'm about halfway through the tutorial. 

One comment I'd have is that for me, it's easier to clone the working app, run it, and then from there explore the files and see how it works rather than building from scratch and adding code one block at a time into an architecture I don't yet fully know/am familiar with. 

So that's how I ended up navigating and using the tutorial, but of course that's just me. But that could be an extra paragraph you add at the beginning where you mention that another way of using this tutorial is to clone the fully working app and read along and explore the files as they are being explained.

---

Edit: now I also realize how this tutorial is not for beginners of Flutter anyway (you jump right into it, and I think that's indeed the right approach, you wouldn't want to get bogged down into explaining how to install Flutter and whatnot). So this is good, but it implies your reader is fairly familiar with mobile apps and Flutter. So I wonder if maybe that's how most people will want to consume the tutorial: clone a fully working sample app, and then follow the tutorial to explore it, rather than "building" it per se. Just my 2 cents.

Also, the app worked on the first try! So that's an absolute awesome dev experience. Congrats, this is really cool.

**Comment by notmandatory** [comment]
I think we should hold off on this blog post until API issues with bdk-flutter (and bdk-rn) can be worked out and more closely aligned with bdk-ffi (and bdk). When I have some time I'll open some issues for your repos, and I see that @thunderbiscuit has already started. I just don't want to get any more confused new folks who want to use rn or flutter when those projects are not ready.

**Comment by BitcoinZavior** [comment]
> ...closely aligned with bdk-ffi (and bdk)...
Ok, I have started aligning the methods in bdk-flutter to bdk-ffi already. Will wait to see what issues get openned before making a PR.

**Comment by notmandatory** [comment]
@BitcoinZavior  it's ok to start making PRs on your projects for aligning the APIs.. just ping me and @thunderbiscuit if you need help and/or review.

**Comment by BitcoinZavior** [comment]
> @BitcoinZavior it's ok to start making PRs on your projects for aligning the APIs.. just ping me and @thunderbiscuit if you need help and/or review.

OK, I will just follow https://github.com/bitcoindevkit/bdk-ffi/blob/master/src/bdk.udl which is what bdk-ffi follows as well.

**Comment by BitcoinZavior** [comment]
> I think we should hold off on this blog post until API issues with bdk-flutter (and bdk-rn) can be worked out and more closely aligned with bdk-ffi (and bdk). When I have some time I'll open some issues for your repos, and I see that @thunderbiscuit has already started. I just don't want to get any more confused new folks who want to use rn or flutter when those projects are not ready.

@notmandatory All code snippets have now been updated to align with the latest bdk-flutter updates, which in turn has been updated to align with ffi api 😊

**Review by thunderbiscuit — APPROVED** [review]
Looks good to me. I recognize all the APIs, and the wallet builds and works locally. I have some questions that are more for my own understanding of the bindings (nothing blocking), which I'll ask on the Discord server.

ACK [dc78b38](https://github.com/bitcoindevkit/bitcoindevkit.org/pull/123/commits/dc78b38d1fa8503151019a9004f574a04c83757c).

**Comment by notmandatory** [comment]
Looks good to me, but can you squash and sign your commits? Then it should be ready to merge. Thanks!

**Comment by notmandatory** [comment]
@BitcoinZavior in our last dev call you mentioned there were a few little updates you wanted to make. Let me know when you think it's ready to go.

**Comment by notmandatory** [comment]
This will also need a final rebase to merge cleanly.

**Comment by BitcoinZavior** [comment]
@notmandatory Finally all done, tested the quickstart app with the published package and made final tweaks.

**Comment by notmandatory** [comment]
@BitcoinZavior It's finally in! thanks for all the updates and testing.

**Pull request merged**
