### PR TITLE
docs/bdk-cli/installation.md:allow for individual copy/paste

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
this change allows each command to be copied individually.

https://deploy-preview-186--awesome-golick-685c88.netlify.app/bdk-cli/installation/

Screenshot 2024-07-05 at 12 06 07 PM

**Comment by notmandatory** [comment]
Concept ACK. We'll be going through all docs once bdk-1.0.0 makes it to first beta release. This is a good thing to keep in mind for any docs where you don't want to run all the commands.

**Comment by RandyMcMillan** [comment]
i will leave this open - rebase as neccesary.

**Comment by RandyMcMillan** [comment]
taking a look at 'key' custom signet support and help output. Add a -n signet --challenge <string> support?

**Comment by RandyMcMillan** [comment]
bdk-cli AFAIK only output valid keys for global signet currently.

**Comment by RandyMcMillan** [comment]
custom signet support ought to be on the v1 roadmap (non blocking but a nice to have)

**Review by thunderbiscuit — APPROVED** [review]
ACK c56e219ead24d29ecfd289def496a745a4b48e04.

**Comment by thunderbiscuit** [comment]
@RandyMcMillan for some reason I can never rebase/force push on your branches I'm not sure why. 

This is my error:
```shell
bitcoindevkit.org on  2021/850814/700297/f65aedb30/b21e96f20-docs/bdk-cli/installation.md [$] is 📦 v1.0.0 via  v21.7.3
❯ git push --force
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push upstream HEAD:refs/pull/186/head

To push to the branch of the same name on the remote, use

    git push upstream HEAD

To choose either option permanently, see push.default in 'git help config'.

To avoid automatically configuring upstream branches when their name
doesn't match the local branch, see option 'simple' of branch.autoSetupMerge
in 'git help config'.
```

I tried both options above and they both don't work. 

I'm not 100% sure this would fix our issue, but would you mind opening PRs that use branches with more standard names, say in this case `docs/cli-fix`?

In any case I just opened a new PR with this commit. #200

**Comment by thunderbiscuit** [comment]
Merged.

**Pull request closed without merging**
