### PR TITLE
Using BDK with Tor

### PR DESCRIPTION
**Pull request by rorp**
Added Tor tutorial

See https://github.com/bitcoindevkit/bdk_wallet/issues/196

### CODE REVIEW

**Comment by notmandatory** [comment]
Thanks for this, a few suggestions:

1. In the first section after explaining how to install tor you should probably also add that it needs to be started in another shell with:
   ```shell
    % tor
    ```
   And then need to wait for the boot strapping to finish.
2. Some of your code examples need the code indents fixed. 
3. You need to sign your commit.
4. You may want to remove the compact block filters example since it takes so long to sync, or at least start with something quicker like electrum, and then show it with cbf. 
5. Since this is a tutorial you should probably move it to the tutorial part of the website

**Comment by notmandatory** [comment]
I've confirmed the CBF, electrum and both esplora sync parts work. But I did have to run the electrum and one of the esplora examples twice after seeing timeouts, most likely tor network related. So probably should mention that if the reader sees a timeout they should try rerunning it. 

I was unable to get the libtor example to build, I'm on an M1 mac and that crate may need to be updated to work with an aarch64 system.

**Comment by rorp** [comment]
> I was unable to get the libtor example to build, I'm on an M1 mac and that crate may need to be updated to work with an aarch64 system.

`libtor` builds Tor from the sources, it's 100% compatible with aarch64 systems. Most likely you don't have autotools and/or libtool installed. I need to update the article with the build instructions.

**Comment by notmandatory** [comment]
> > I was unable to get the libtor example to build, I'm on an M1 mac and that crate may need to be updated to work with an aarch64 system.
> 
> `libtor` builds Tor from the sources, it's 100% compatible with aarch64 systems. Most likely you don't have autotools and/or libtool installed. I need to update the article with the build instructions.

I fixed my build problem, I had to set these env variables, now builds fine:
```shell
export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
```

**Comment by notmandatory** [comment]
You'll also need to update the `config.js` file to add your tutorial to the sidebar list.

**Review by notmandatory — APPROVED** [review]
ACK 35a6e6432afae6249efbc6afea22e3c69414865e

All example code works for me, thanks for the updates. We will need to hold off on merging until https://github.com/bitcoindevkit/bdk/pull/816 goes in so the link to the example code is available.

**Comment by thunderbiscuit** [comment]
Is this ready to go in? @rorp @notmandatory let's get it in if we can and the content is still relevant.

**Comment by notmandatory** [comment]
@thunderbiscuit sorry for the slow response, yes let's merge this. It's great info and will be something we want to incorporate into a future user bdk user guide.

**Pull request merged**
