### PR TITLE
blog: add call for proposals, rust maintainer

### PR DESCRIPTION
**Pull request by notmandatory**

### CODE REVIEW

**Review by reez — APPROVED** [review]
ACK 62b7dc8152bb62dca46bcb7c88a3168722c8b99c

The "social media" post about this are scheduled to go out Aug 26.

Can merge this now, or can wait until Aug 26, whatever you think.

This looks great I'm excited for it!

**Comment by reez** [comment]
Ready for merge, just needs rebase-

**Comment by notmandatory** [comment]
I've rebased on master and will merge this as soon as tests finish.

**Comment by reez** [comment]
cool!

**Pull request merged**
