### PR TITLE
Adoption: proton wallet

### PR DESCRIPTION
**Pull request by reez**
Pending OK from Proton Wallet

### CODE REVIEW

**Comment by notmandatory** [comment]
Please also add them to the "Web" section. :-)

**Comment by reez** [comment]
> Please also add them to the "Web" section. :-)

will do right now, thanks!!

**Comment by notmandatory** [comment]
I got the OK from my contact at Proton but he'd like to use for the blurb:
```
A self-custodial Bitcoin wallet from the makers of Proton Mail.
```

Also I'd like to see if we can find a .png for the logo with a transparent background so the logo doesn't have the white box when in dark mode.  I'll ask one of their designers if they can help get one for us.

**Comment by reez** [comment]
> I got the OK from my contact at Proton but he'd like to use for the blurb:
> 
> ```
> A self-custodial Bitcoin wallet from the makers of Proton Mail.
> ```

great! updated the blurb.

**Comment by notmandatory** [comment]
Here are some official logos from Proton, I think the transparent PNG will look best but give it a try. 

[Proton-Wallet-logos.zip](https://github.com/user-attachments/files/16964341/Proton-Wallet-logos.zip)

**Review by notmandatory — APPROVED** [review]
ACK 765a178f7618451f1bf3c1871ff90cba08047e5c

I tested in light and dark mode and both look good!

**Pull request merged**
