### PR TITLE
[Tutorial] Updated exploring bdk flutter tutorial code

### PR DESCRIPTION
**Pull request by anipy1**
Hello! I've made some updates to the exploring_bdk_flutter tutorial code in order to align it with the `bdk_flutter: ^0.28.2` version of the package API. This should help resolve the issues that were encountered during the [Twitch stream](https://www.twitch.tv/videos/1846999911) following the tutorial, where the tutorial was using an outdated version of the code.

With these updates, developers who are following the tutorial will be able to avoid the problems encountered during the stream and have a smoother experience while building their first app using `bdk_flutter`.

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
@BitcoinZavior would you mind reviewing this? I'm trying to get all PRs for the website cleaned up this week. Cheers!

**Review by BitcoinZavior — APPROVED** [review]

**Comment by BitcoinZavior** [comment]
Thanks for the PR @aniketambore much appreciated 👍

**Comment by BitcoinZavior** [comment]
@aniketambore would you be able to rebase this with the latest master branch, please?

**Comment by thunderbiscuit** [comment]
I'll rebase and merge.

**Pull request merged**
